#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mash
Version  : 0.6.19
Release  : 30
URL      : http://pkgs.fedoraproject.org/repo/pkgs/mash/mash-0.6.19.tar.gz/9c72ff746ee287957b2885ed7ccf162e/mash-0.6.19.tar.gz
Source0  : http://pkgs.fedoraproject.org/repo/pkgs/mash/mash-0.6.19.tar.gz/9c72ff746ee287957b2885ed7ccf162e/mash-0.6.19.tar.gz
Summary  : Build system -> repository tool
Group    : Development/Tools
License  : GPL-2.0
Requires: mash-bin
Requires: mash-license
Requires: mash-data
Requires: mash-python
Requires: mash-legacypython
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
Patch1: 0001-Use-createrepo_c.patch

%description
mash is a tool that queries a koji buildsystem for the latest RPMs for
any particular tag, and creates repositories of those RPMs, including
any multlib RPMs that are necessary.

%package bin
Summary: bin components for the mash package.
Group: Binaries
Requires: mash-data
Requires: mash-license

%description bin
bin components for the mash package.


%package data
Summary: data components for the mash package.
Group: Data

%description data
data components for the mash package.


%package legacypython
Summary: legacypython components for the mash package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the mash package.


%package license
Summary: license components for the mash package.
Group: Default

%description license
license components for the mash package.


%package python
Summary: python components for the mash package.
Group: Default

%description python
python components for the mash package.


%prep
%setup -q -n mash-0.6.19
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536701381
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/mash
cp COPYING %{buildroot}/usr/share/doc/mash/COPYING
python2 -tt setup.py build -b py2 install --root=%{buildroot}
## install_append content
mv %{buildroot}/usr/bin/mash.py %{buildroot}/usr/bin/mash
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mash

%files data
%defattr(-,root,root,-)
/usr/share/mash/spam-o-matic

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(-,root,root,-)
/usr/share/doc/mash/COPYING

%files python
%defattr(-,root,root,-)
